inherit_from:
  - .rubocop_airbnb.yml

Rails:
  Enabled: true

AllCops:
  NewCops: enable
  Exclude:
  - 'bin/*'
  - 'config/**/*'
  - 'db/**/*'
  - 'script/**/*'
  - 'spec/spec_helper.rb'
  - 'node_modules/**/*'
  - 'vendor/**/*'
  - '.git/**/*'
  - '**/Gemfile'
